# NOTE: "base_link" is the center of the rear axle projected on the ground
# NOTE: "sensor_kit_base_link" is the geometric center of the vehicle (Audi-Q8)
base_link:
  sensor_kit_base_link:
    x: 1.4065
    y: 0.0
    z: 0.8165
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
